"""create initial tables

Revision ID: 06f2ed865add
Revises: 
Create Date: 2023-01-04 21:18:40.856504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# before running alembic head, CREATE EXTENSION "uuid-ossp" for db.

# revision identifiers, used by Alembic.
revision = '06f2ed865add'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
        sa.Column('employee_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('password', sa.String(), nullable=True),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('shift_data',
        sa.Column('shift_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
        sa.Column('employee_id', postgresql.UUID(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
        sa.PrimaryKeyConstraint('shift_id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_data')
    op.drop_table('employee')
    # ### end Alembic commands ###
