"""Create lunch and break data

Revision ID: 9ae73dd373af
Revises: 06f2ed865add
Create Date: 2023-01-04 23:33:40.985804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ae73dd373af'
down_revision = '06f2ed865add'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('break_data',
        sa.Column('break_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
        sa.Column('shift_data_id', postgresql.UUID(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['shift_data_id'], ['shift_data.shift_id'], ),
        sa.PrimaryKeyConstraint('break_id')
    )
    op.create_table('lunch_data',
        sa.Column('lunch_break_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
        sa.Column('shift_data_id', postgresql.UUID(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['shift_data_id'], ['shift_data.shift_id'], ),
        sa.PrimaryKeyConstraint('lunch_break_id')
    )
    op.add_column('shift_data', sa.Column('on_lunch', sa.Boolean(), nullable=True))
    op.add_column('shift_data', sa.Column('on_break', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_data', 'on_break')
    op.drop_column('shift_data', 'on_lunch')
    op.drop_table('lunch_data')
    op.drop_table('break_data')
    # ### end Alembic commands ###
